### ISSUE TITLE
Hackathon 01062016

### ISSUE THREAD

**Issue by Woda1011** [Woda1011/IWISmartCoffee#43]
- [x] Display wird beim Kaffeezapfen manchmal zerschossen
- [ ] Mapping der CampusCard mit dem Server via WebSocket
- [ ] Gaaaaaaaaaaaaanz am Ende den Code hübsch machen (wenn noch Zeit :hourglass: )
- [x] Prototyp Eimer bauen 
- [x] Wie sieht es aus mit der FlowRate vom Kaffee?
- [x] Datenbank anpassen für CampusID als string
- [x] Verkabelung optimieren
- [x] Verkabelung in Fritzing dokumentieren
- [x] Systemuser hinterlegen

**Comment by Woda1011** [comment]
Display Bug Tritt wohl auf, aufgrund unsauberer Verkabelung

**Comment by grpe1012** [comment]
@Woda1011 mM nach Tritt der Display Bug nicht aufgrund unsauberer Verkablung sondern aufgrund Mehrfachbelegungen an einem 5V Anschluss auf. Verkabelung wurde geändert. Seit da Bug nichtmehr aufgetreten.

**Comment by grpe1012** [comment]
Weitere ToDos:
- [ ] Nutzerregistration
- [x] Codes Generieren + PDF zum ausdrucken
- [x] Nutzer läd über WebApp Kaffeekonto auf

**Comment by kleinMaggus** [comment]
@grpe1012 
Codes generieren und Nutzerkonto aufladen geht doch schon?

**Comment by grpe1012** [comment]
- [ ] Kaffemenge in Maschine aktuell halten 
- Wenn neuer Kaffee gemacht wird, setzt Admin in Admin-Frontend Kaffeeanzahl [wird in DB als Eintrag mit Tiestamp gespeichert]
- Jede Minute von Pi zu Backend 1 Request welcher Kaffeemenge abgleicht, so wird abgesichert, dass richtige Kaffeemenge auch nach Auffüllen an Pi steht
- 30mins nachdem der Kaffe gemacht wurde ist das Kaffeezapfen gesperrt [Meldung Kaffee wird gebrüht noch 23:31mins]
- wird Kaffee gezapft, wird Menge in Backend und Pi aktualisiert.

**Comment by Woda1011** [comment]
@flyingfeet ja die Dinge funktionieren :grin: 

Ich schließe den Issue und pack die offenen Dinge in neue Issues
