### ISSUE TITLE
CampusCard Mapping API

### ISSUE THREAD

**Issue by Woda1011** [Woda1011/IWISmartCoffee#47]
Für das Mapping wird ein Websocket vom Frontend zum Backend geöffnet. Sobald der PI eine Karte erkennt schickt dieser einen GET-Request mit der CampusCardId zum backend um die passenden Daten zu siehen. Bei diesem GET weiß der Server welche Karte gesetzt ist. 
- Beim GET-Request die aktuelle CampusCardId auf dem Server setzen
- Schnittstelle um den API von der aktuellen CampusCardId zu "befreien"
- einmaliger Aufruf der löschen API vom PI, wenn die CampusCard nicht mehr auf dem gerät liegt

**Comment by Woda1011** [comment]
@flyingfeet wenn du die neue API für das Löschen der aktuellen CampusCardID auf dem Server hast sag bescheid, dann baue ich das bei mir ein.
Hierfür reicht ja ein einfacher GET auf eine bestimmte URL

**Comment by kleinMaggus** [comment]
@Woda1011 
Gepusht. Das "Befreien" ist per GET unter /api/campuscard möglich

**Comment by Woda1011** [comment]
done
