### ISSUE TITLE
Nutzerregistration

### ISSUE THREAD

**Issue by Woda1011** [Woda1011/IWISmartCoffee#50]
Da der Kaffee-Admin nur noch das Mapping der CampusCard übernimmt (see #48 ), muss sich ein Student selbst einen Account anlegen können. Dazu einfach unter dem Login-Button einen Registrieren Button hinzufügen. Theoretisch existiert die Api dafür schon, aber so kann quasi auch ein Bot 1000 User anlegen. 
- Anlegen via Bestätigungsmail usw.?

**Comment by kleinMaggus** [comment]
https://www.npmjs.com/package/angular2-google-recaptcha fehlt noch, sonst done, nur nicht gepushed wegen hska-proxy^^
